### ISSUE TITLE
Setup Admin UI project

### ISSUE THREAD

**Issue by noce2cicd** [math-dojo/admin-web-ui#2]
- [x] The admin-web-ui angular project is setup
- [x] The CICD pipeline for testing and deploying the web application is set up and status checks are placed on commits

**Comment by noce2cicd** [comment]
@aakano684 please could you point to the commit that wrapped this issue up? That way we can come back to it should we need to?

**Comment by aakano684** [comment]
[This commit](https://github.com/math-dojo/admin-web-ui/commit/cd36f633eb7b5450b66a3f47eb3e4973cf490983) wrapped up the issue.
